apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: softcon-aiops-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: softcon-aiops-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: aiops
  labels:
    app.kubernetes.io/part-of: softcon-aiops-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app.kubernetes.io/part-of: softcon-aiops-demo
