crds:
  create: false

alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy

  enableReporting: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

controller:
  type: deployment
  replicas: 1

service:
  enabled: true
  type: ClusterIP
