multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/compactor
  compaction_interval: 5m

limits:
  ingestion_rate: 1000000
  ingestion_burst_size: 2000000
  max_global_series_per_user: 100000
